import type { EquipmentCatalogItem } from "@/lib/home/types";

export const equipmentPdfPath = encodeURI("/docs/прайс все позиции в сомах.pdf");

export const equipmentCatalogDefaults: EquipmentCatalogItem[] = [
  {
    id: "pos-monoblocks",
    title: "POS-моноблоки",
    description: "Кассовые рабочие станции для розницы и общепита.",
    shortLabel: "POS",
    inStock: null,
    unit: "шт",
  },
  {
    id: "barcode-scanners",
    title: "Сканеры штрих-кодов",
    description: "Ручные и стационарные сканеры для кассовой зоны.",
    shortLabel: "SCAN",
    inStock: null,
    unit: "шт",
  },
  {
    id: "receipt-printers",
    title: "Принтеры чеков",
    description: "Фискальные и нефискальные чековые принтеры.",
    shortLabel: "CHK",
    inStock: null,
    unit: "шт",
  },
  {
    id: "label-printers",
    title: "Принтеры этикеток",
    description: "Печать термоэтикеток для маркировки товаров.",
    shortLabel: "LBL",
    inStock: null,
    unit: "шт",
  },
  {
    id: "scales",
    title: "Весы с печатью этикеток",
    description: "Весовое оборудование для магазина и склада.",
    shortLabel: "WGT",
    inStock: null,
    unit: "шт",
  },
  {
    id: "cash-drawers",
    title: "Денежные ящики",
    description: "Надежные кассовые ящики под разные кассы.",
    shortLabel: "CASH",
    inStock: null,
    unit: "шт",
  },
  {
    id: "tsd",
    title: "ТСД (терминалы сбора данных)",
    description: "Мобильные терминалы для учета и инвентаризации.",
    shortLabel: "TSD",
    inStock: null,
    unit: "шт",
  },
  {
    id: "anti-theft",
    title: "Противокражные системы",
    description: "Рамки и метки для защиты товарных зон.",
    shortLabel: "SEC",
    inStock: null,
    unit: "компл",
  },
  {
    id: "thermal-labels",
    title: "Термоэтикетки",
    description: "Расходные материалы для печати этикеток.",
    shortLabel: "THM",
    inStock: null,
    unit: "рул",
  },
  {
    id: "receipt-tape",
    title: "Чековые ленты",
    description: "Чековая термолента разных форматов.",
    shortLabel: "RCP",
    inStock: null,
    unit: "рул",
  },
  {
    id: "peripheral-devices",
    title: "Периферийные устройства",
    description: "Клавиатуры, мыши, кабели, адаптеры и прочая периферия.",
    shortLabel: "PRPH",
    inStock: null,
    unit: "шт",
  },
];
